### ISSUE TITLE
IllegalStateException in LookupMetaData

### ISSUE THREAD

**Issue by dstuebe** [upserve/uppend#68]
```java.lang.IllegalStateException: expected 780 keys, got 653 at path: data/gastronomer/uppend/GuestLookup/lookups/37/02/meta
	at com.upserve.uppend.lookup.LookupMetadata.<init>(LookupMetadata.java:55)
	at com.upserve.uppend.lookup.LongLookup.getUncachedInternal(LongLookup.java:333)
	at com.upserve.uppend.lookup.LongLookup.get(LongLookup.java:114)
	at com.upserve.uppend.FileAppendOnlyStore.blockPos(FileAppendOnlyStore.java:186)
	at com.upserve.uppend.FileAppendOnlyStore.blockValues(FileAppendOnlyStore.java:164)
	at com.upserve.uppend.FileAppendOnlyStore.read(FileAppendOnlyStore.java:52)```

**Comment by dstuebe** [comment]
[meta.zip](https://github.com/upserve/uppend/files/1633184/meta.zip)
[data.zip](https://github.com/upserve/uppend/files/1633185/data.zip)
[keys.zip](https://github.com/upserve/uppend/files/1633186/keys.zip)

**Comment by dstuebe** [comment]
Long lookup and block issues have been fixed.
